/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppRepositorioRouteImport } from './routes/_app.repositorio'
import { Route as AppChatRouteImport } from './routes/_app.chat'
import { Route as AppCargarRouteImport } from './routes/_app.cargar'
import { Route as AppBuscarRouteImport } from './routes/_app.buscar'
import { Route as AppDocumentosDocIdRouteImport } from './routes/_app.documentos.$docId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppRepositorioRoute = AppRepositorioRouteImport.update({
  id: '/repositorio',
  path: '/repositorio',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppCargarRoute = AppCargarRouteImport.update({
  id: '/cargar',
  path: '/cargar',
  getParentRoute: () => AppRoute,
} as any)
const AppBuscarRoute = AppBuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentosDocIdRoute = AppDocumentosDocIdRouteImport.update({
  id: '/documentos/$docId',
  path: '/documentos/$docId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/buscar': typeof AppBuscarRoute
  '/cargar': typeof AppCargarRoute
  '/chat': typeof AppChatRoute
  '/repositorio': typeof AppRepositorioRoute
  '/documentos/$docId': typeof AppDocumentosDocIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/buscar': typeof AppBuscarRoute
  '/cargar': typeof AppCargarRoute
  '/chat': typeof AppChatRoute
  '/repositorio': typeof AppRepositorioRoute
  '/': typeof AppIndexRoute
  '/documentos/$docId': typeof AppDocumentosDocIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/buscar': typeof AppBuscarRoute
  '/_app/cargar': typeof AppCargarRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/repositorio': typeof AppRepositorioRoute
  '/_app/': typeof AppIndexRoute
  '/_app/documentos/$docId': typeof AppDocumentosDocIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/buscar'
    | '/cargar'
    | '/chat'
    | '/repositorio'
    | '/documentos/$docId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/buscar'
    | '/cargar'
    | '/chat'
    | '/repositorio'
    | '/'
    | '/documentos/$docId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/buscar'
    | '/_app/cargar'
    | '/_app/chat'
    | '/_app/repositorio'
    | '/_app/'
    | '/_app/documentos/$docId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/repositorio': {
      id: '/_app/repositorio'
      path: '/repositorio'
      fullPath: '/repositorio'
      preLoaderRoute: typeof AppRepositorioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cargar': {
      id: '/_app/cargar'
      path: '/cargar'
      fullPath: '/cargar'
      preLoaderRoute: typeof AppCargarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/buscar': {
      id: '/_app/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof AppBuscarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documentos/$docId': {
      id: '/_app/documentos/$docId'
      path: '/documentos/$docId'
      fullPath: '/documentos/$docId'
      preLoaderRoute: typeof AppDocumentosDocIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBuscarRoute: typeof AppBuscarRoute
  AppCargarRoute: typeof AppCargarRoute
  AppChatRoute: typeof AppChatRoute
  AppRepositorioRoute: typeof AppRepositorioRoute
  AppIndexRoute: typeof AppIndexRoute
  AppDocumentosDocIdRoute: typeof AppDocumentosDocIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBuscarRoute: AppBuscarRoute,
  AppCargarRoute: AppCargarRoute,
  AppChatRoute: AppChatRoute,
  AppRepositorioRoute: AppRepositorioRoute,
  AppIndexRoute: AppIndexRoute,
  AppDocumentosDocIdRoute: AppDocumentosDocIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
